# fly.toml app configuration file generated for nhl-browser on 2026-05-11T10:46:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nhl-browser'
primary_region = 'iad'

[build]

[env]
  DASH_ENABLE_SECURITY_HEADERS = '1'
  DATA_DIR = '/app/runtime_data'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
